version: "3.2"

services:

  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    build: .
    container_name: application
    env_file:
      - .env
    depends_on:
      - database

  nginx:
    image: nginx:1.19.3
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data:
